{{ config(materialized='table') }}

WITH base_data AS (
    SELECT
        s_no,
        mrno,
        patient_name,
        patient_age,
        patient_gender,
        mobile_no,
        department,
        doctor,
        doctor_level,
        consultation_date,
        consultation_type,
        unit,
        visit_no,
        billed_status,
        invoice_no,
        queue_generation_time,
        queue_no,
        start_consultation_time,
        end_consultation_time,
        sponsor_name,
        plan,
        associate_company,
        registered_patient_id,
        registered_patient_age,
        date_of_birth,
        registered_patient_gender,
        diagnosis AS original_diagnosis,
        registered_mobile_no,
        calculated_age,
        age_group,
        parent_guardian_phone,
        parent_guardian_age,
        parent_guardian_city,
        parent_guardian_district,
        parent_guardian_state,
        parent_guardian_country,
        who_brought_the_child,
        location_category,
        pat_idn_no,
        guardian_pin,
        plan_name,
        is_processed,
        updated_date,
        inserted_date,
        identity_type,
        patient_income,
        registration_type,
        service_center_name,
        consultation_category,
        dep_consult_category,
        dep_shortened,
        year,
        financial_year,
        month,
        quarter,
        -- Generate session_id using row_number
        ROW_NUMBER() OVER (ORDER BY s_no, mrno, consultation_date) AS session_id
    FROM {{ ref('clinic_bay_mgmt') }}
),

-- Split diagnosis while respecting parentheses
diagnosis_split AS (
    SELECT 
        *,
        -- Use regex to split on commas that are not within parentheses
        -- This regex looks for commas followed by optional spaces that are not preceded by an unclosed parenthesis
        REGEXP_SPLIT_TO_TABLE(
            original_diagnosis, 
            ',(?![^()]*\))'
        ) AS diagnosis
    FROM base_data
    WHERE original_diagnosis IS NOT NULL 
    AND TRIM(original_diagnosis) != ''
),

-- Clean up the split diagnoses and remove duplicates
cleaned_diagnosis AS (
    SELECT 
        s_no,
        mrno,
        patient_name,
        patient_age,
        patient_gender,
        mobile_no,
        department,
        doctor,
        doctor_level,
        consultation_date,
        consultation_type,
        unit,
        visit_no,
        billed_status,
        invoice_no,
        queue_generation_time,
        queue_no,
        start_consultation_time,
        end_consultation_time,
        sponsor_name,
        plan,
        associate_company,
        registered_patient_id,
        registered_patient_age,
        date_of_birth,
        registered_patient_gender,
        original_diagnosis,
        TRIM(diagnosis) AS diagnosis,
        registered_mobile_no,
        calculated_age,
        age_group,
        parent_guardian_phone,
        parent_guardian_age,
        parent_guardian_city,
        parent_guardian_district,
        parent_guardian_state,
        parent_guardian_country,
        who_brought_the_child,
        location_category,
        pat_idn_no,
        guardian_pin,
        plan_name,
        is_processed,
        updated_date,
        inserted_date,
        identity_type,
        patient_income,
        registration_type,
        service_center_name,
        consultation_category,
        dep_consult_category,
        dep_shortened,
        year,
        financial_year,
        month,
        quarter,
        session_id
    FROM diagnosis_split
    WHERE TRIM(diagnosis) != ''
),

-- Remove duplicate diagnoses for the same session
deduplicated_diagnosis AS (
    SELECT DISTINCT
        s_no,
        mrno,
        patient_name,
        patient_age,
        patient_gender,
        mobile_no,
        department,
        doctor,
        doctor_level,
        consultation_date,
        consultation_type,
        unit,
        visit_no,
        billed_status,
        invoice_no,
        queue_generation_time,
        queue_no,
        start_consultation_time,
        end_consultation_time,
        sponsor_name,
        plan,
        associate_company,
        registered_patient_id,
        registered_patient_age,
        date_of_birth,
        registered_patient_gender,
        original_diagnosis,
        diagnosis,
        registered_mobile_no,
        calculated_age,
        age_group,
        parent_guardian_phone,
        parent_guardian_age,
        parent_guardian_city,
        parent_guardian_district,
        parent_guardian_state,
        parent_guardian_country,
        who_brought_the_child,
        location_category,
        pat_idn_no,
        guardian_pin,
        plan_name,
        is_processed,
        updated_date,
        inserted_date,
        identity_type,
        patient_income,
        registration_type,
        service_center_name,
        consultation_category,
        dep_consult_category,
        dep_shortened,
        year,
        financial_year,
        month,
        quarter,
        session_id
    FROM cleaned_diagnosis
)

SELECT * FROM deduplicated_diagnosis
ORDER BY session_id, diagnosis
