version: 2

sources:
  - name: source_ummeed_ict_health
    schema: ict_health_staging
    tables:
      - name: registered_patient
        identifier: registeredPatient
        description: registered patient on ICT health app

      - name: clinic_bay_management_data
        identifier: clinicData
        description: patient data

      - name: appointment_details
        identifier: appointmentDetails
        description: appointment data
      
      - name: dim_department_acronym
        identifier: dim_department_acronym
        description: departments and their acronyms

      - name: dim_consultation_type_mapping
        identifier: dim_consultation_type_mapping
        description: consultation types mapped to their category

  - name: source_ummeed_synergy_connect
    schema: staging_synergy_connect 
    tables:
      - name: participant_impact
        identifier: Participant_Impact
        description: participant details from synergy connect app

      - name: no_registrations
        identifier: no_registrations
        description: participant details who has aggregated data
      

